.travis.yml
django-quilla.lektorproject

Cree el archivo .travis.yml
Modifique el archivo .lektorproject

Configurando Travis

---

README.md

Agregadas instrucciones de ejecución

---

.travis.yml

Modificaciones al .travis.yml con ayuda de @Scot3004

Agregue versoin de nodejs y el TZ para America/Bogota

---

content/about/contents.lr

Cambio twitter javier

---

content/blog/como-fue-organizar-primer-django-girls-barranquilla/contents.lr

Agregué imagen de patrocinadores y corregí parte del texto.

Editando articulo Django Girls Barranquilla 2017

---

content/blog/como-fue-organizar-primer-django-girls-barranquilla/contents.lr

Quite las etiquetas p al final para las italicas

---

README.md

Enlace hacia el código de conducta en el README

---

content/blog/como-fue-organizar-primer-django-girls-barranquilla/contents.lr
content/blog/first-post/contents.lr
models/blog-post.ini
templates/blog.html

Agregue nuevo campo excerpt para mostrar un pequeño fragmento del articulo en la vista blog.

Mostrar fragmento de articulo en vista blog

---

index.html
templates/layout.html

Corregí el enlace hacia el inicio en el menu y en el logo. close #55

Corregi enlace hacia el home en el logo

---

templates/layout.html

Agregado en la plantilla base (layout.html)

Codigo de Google Analytics

---

content/contents.lr
content/eventos/contents.lr
templates/layout.html

Agregue seccion de eventos + Cambie img principal

---

content/eventos/contents.lr

Cambie los enlaces de html a markdown, debido a que el parse markdown to html estaba encerrando los vinculos en otro vinculo. Ej: <a href"<a href"...">

Fix enlaces en la pagina de eventos

---

content/blog/reconomiento-rostros/contents.lr
index.html
templates/blog-post.html
templates/layout.html
templates/page.html

Cambie la url del articulo sobre reconocimiento de rostros y añadi un script para agregar target='_blank' a todos los links de cada uno de los post y en la pagina de eventos.

Cambio de url y adicion de target="_blank"

---

CONTRIBUTING.md
README.md

Fix: #20. Añadi archivo CONTRIBUTING.md con las reglas para contribuir al repositorio y modifique el README.md para incluir un link a estas normas.

Añadi archivo CONTRIBUTING.md

---

content/blog/primeros-pasos-en-python/contents.lr
content/contents.lr
content/eventos/contents.lr

- Correcciones a errores en articulo primeros pasos en Python
- Coloque efecto de hover en la imagen principal. Para distinguir que puede hacersele click
- Cambie de markdown a HTML la tabla de eventos en 'Eventos'

Correcciones en Primer pasos en Python y mejoras en CSS

---

.travis.yml
django-quilla.lektorproject
requirements.txt

No he podido replicar el error que sale al hacer build (ya descargue de nuevo el proyecto e hice lektor build -f webpack), lo que si encontre es que en el commit [249fbc2507fdd372a6328ee59299f4badbc56180](https://github.com/lektor/lektor-webpack-support/commit/249fbc2507fdd372a6328ee59299f4badbc56180#diff-ddaefad86cd14f22866ffcb93cb3bca8) la gente de lektor-webpack-support cambio la linea que esta fallando.

Fix lektor versions

---

content/404.html/contents.lr
templates/404.html

404 personalizado

---

content/contents.lr
content/eventos/contents.lr

Mantenimiento. No tiene un issue asociado

Agregue PDF de ultimo evento y actualice portada del home

---

templates/hacktoberfest-2018.html

Relacionado a #153
Agregue charla, removí enlace a FAQ y cambie texto de enlace en el botón principal

Hacktoberfest

---

templates/hacktoberfest-2018.html

Acá realicé algunas correciones ortográficas a la página de Hacktoberfest
Closes #(numero de issue)
Escribe o adjunta una imagen de la información que considere pertinente del cambio que se está subiendo, por ejemplo una captura de pantalla en algún cambio visual.

Propuesta de correciones

---

README.md

#180  Pull request
Closes #180 
-Se agrego a la documentación como solucionar el problema con las variables de entornos de UTF-8 de los idiomas de ingles y español para poder ejecutar lektor y el proyecto sin problemas en algunos macOS donde se presente el inconveniente.

Se agrego a la documentación para problema con las variables UTF-8 python

---

templates/hacktoberfest-2018.html

Relacionado a #182 
formato correcto de la img es jpg

Edite formato imagen monokuko

---

content/about/contents.lr

fix: 🐛 Organizadores imagenes ya no se estiran

---

content/eventos/contents.lr

Closes #194 
Lo hice por el admin de lektor. No se si sea la mejor forma

Actualice ppts de eventos recientes 2018

---

content/blog/primeros-pasos-en-python/contents.lr

Closes #195 
El enlace no era el correcto

Corregido enlace de articulo de primeros pasos en Python

---

.travis.yml

Intento de corregir los build fallidos
Eliminados los pasos que usan curl que de momento no están funcionando, la pagina no se refresco la ultima vez

Removed curl for events in PR

---

.gitignore
content/contact/contents.lr

Se incluye en la sección de contactos invitación y links a formularios para postulación de charlas, solicitudes de nuevos voluntarios y de escritores de la comunidad.

formularios de voluntarios en sección contacto

---

templates/blog-post.html
templates/blog.html

Closes #224 
Eliminado sidebar de los post 
Centrado el listado de posts

Eliminado sidebar del blog

---

content/blog/como-fue-organizar-primer-django-girls-barranquilla/contents.lr

Closes #238 
Se corrigen algunos enlaces y enlaces de fotos que estaban incorrectos.

Se corrigieron enlaces y enlaces de fotos

---

content/blog/una-guia-completa-de-django-para-principiantes-parte-2/contents.lr
content/contents.lr

Closes #252 
Se modifican las rutas de las imágenes para que puedan ser visualizadas en el articulo

Serie django articulo 2

---

content/eventos/contents.lr

Closes #208 
Se adicionan los anexos de las Diapositivas y GitHub según los comentarios del Issue.
Se adjunta resultado de w3c_validator.
[w3c_validator.txt](https://github.com/PyBAQ/django-quilla-web/files/5077288/w3c_validator.txt)

Agregar los anexos para las presentaciones del 2019

---

content/hacktoberfest-2018/contents.lr
content/hacktoberfest-2018/faq/contents.lr
templates/hacktoberfest-2018.html

Closes #256 
Resuelve el render de la plantilla del Hacktoberfest 2018

Close #256. Hacktoberfest 2018

---

content/nosotros/contents+en.lr
flowblocks/link.ini
flowblocks/three-columns.ini
flowblocks/two-columns.ini
templates/blocks/link.html

Traducida pagina nosotros

---

content/contents+en.lr
content/contents.lr

Mensaje de eventos vacio en home

---

content/contacto/contents+en.lr
content/contacto/contents.lr
content/contents+en.lr
content/contents.lr

Fix texto próximos eventos

---

Dockerfile
README.md

Closes #275 
Se cambió la imagen de python en el Dockerfile quedando python:slim-buster.
Se ejecutó localmente con docker y al consultar dentro del contenedor la versión de python confirmó que la versión es 3.9.3. Se verificó y el proyecto se está ejecutando correctamente.

Docker python slim buster #275

---

databags/settings.json
templates/blog-post.html
templates/blog.html

Closes #278 
Con este se entrega el ultimo item que requiere pull request para el milestone i18n

Traducción metadata blog

---

content/codigo-de-conducta/contents.lr

Closes #284 
Se corrige Django por Python Barranquilla y el correo electrónico en el Código de Conducta.

Se corrige Django por Python Barranquilla y el correo electronico

---

content/blog/primeros-pasos-en-python/contents.lr

Actualización de vinvulos en articulo "Primeros Pasos".
Simplemente quito los vintulos que no funcionan y agrego un vinculo de aprendizaje de python.

Actualicé cinvulos de articulo primeros pasos

---

content/blog/liga-python/contents.lr

Fix
Estar mas pendientes. Los términos y referencias son clave para el concurso

Terminos de referencia Liga Python

---

.gitignore
README.md
pytest.ini
requirements.txt
test-requirements.txt
tests/test_home.py

Closes #64 
Ejecución de tests automatizados

Pytest selenium setup

---

.travis.yml
requirements.txt

Closes #309 
Se actualizan las versiones en el archivo requirements.txt y la versión de python en .travis.yml a python 3.9

update lektor flask requests and Werkzeug

---

templates/layouts/footer.html

Closes #311 
Se adicionan los iconos de Discord y YouTube, se retira icono de Slack, se reorganizan iconos, se actualiza la referencia de los mismos a Font Awesome 6.1.0.

Adicionar discord y youtube

---

templates/layouts/footer.html

Closes #323 
Agregar icono Linkedin.

Agregar icono linkedin

---

requirements.txt

Nueva versión de Flask, lektor y werkzeug
Closes #330 
Arreglar el build al actualizar las versiones de los paquetes

Se actualiza requirements para evitar error en build. 

---

content/blog/caminemos-juntos-1er-paso-99-bottles-of-beer-song/contents.lr

Closes #333
Se arregla código del Blog post Caminemos Juntos: Primer Paso "99 Bottles of Beer song". Existen dos excepciones en ejercicio y no solo una.

Arreglar error del ejercicio cuando x==2 bottles

---

content/codigo-de-conducta/contents+en.lr

Closes #317 
Versión en inglés del Código de conducta.

Agregar código de conducta en inglés

---

README.md

Corregir instrucciones del README.md

---

content/eventos/contents.lr

Se actualiza enlaces, github y recursos de ultimos eventos de 2022

---

django-quilla.lektorproject

Update the repo name with PyBAQ/website

---

.travis.yml

se añade token para el deploy

---

.travis.yml
django-quilla.lektorproject

Closes #356 
Cambiar configuración en travis.yml según:
- https://www.getlektor.com/docs/deployment/ghpages/
- https://www.getlektor.com/docs/deployment/travisci/

Target is ghpages with SSH

---

.travis.yml
django-quilla.lektorproject

Fix deploy2

---

.travis.yml

Relates to issue #356 
Probando nuevo token en travis

testing new token in travis

---

content/contacto/contents+en.lr
content/contacto/contents.lr

Borrado el enlace que llama a escribir artículos

---

templates/layouts/js_files.html
templates/macros/blog.html

Closes #374 
Tweemoji ya carga con este pr
Elimine un comentario en el código para que el pr donde se va a borrar todo no se vea tan grande, igual es un cambio en un comentario, no deberia afectar

Tweemoji cambio de cdn

---

assets/robots.txt
content/404.html/contents.lr
content/sitemap.xml/contents.lr
models/hacktoberfest-2018.ini
requirements.txt
templates/hacktoberfest-2018.html
templates/hacktoberfest-2020.html
templates/layout.html
templates/sitemap.xml

Closes #325 #326 
El siguiente sitemap fue autogenerado, tiene loc, y traducciones, en cuanto al campo lastmodified la verdad me dio mucha lidia tratando de agregarlo y dado que no es estrictamente necesario que este en el sitemap y es mas bien un campo opcional e informativo, se la dejo al que quiera aprender a hacerlo
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://pybaq.co/</loc>
<xhtml:link rel="alternate" hreflang="es" href="https://pybaq.co/"/>
<xhtml:link rel="alternate" hreflang="en" href="https://pybaq.co/en/"/>
<priority>0.64</priority>
</url>
<url>
<loc>https://pybaq.co/blog/</loc>
<xhtml:link rel="alternate" hreflang="es" href="https://pybaq.co/blog/"/> …
```

325 sitemap

---

Dockerfile

Closes #382 
Con los cambios se puede ejecutar docker. Tiene en cuenta los archivos requirements.txt y test-requirements.txt según se requiera.

Corregir Dockerfile instale requirements.txt y test-requirements.txt

---

assets/robots.txt

Closes #326
Dado que solo se menciono dicha imagen en el issue, solo anexo esta

Disallow Diaspositiva imagen diaspositiva 26

---

.gitignore
tests/features/test_homepage.py

Closes #387 
Toma un screenshot del homepage antes de hacer las vericaciones
Aca se ve la ejecución de los test en mi ramita :)
chrome
https://github.com/Scot3004/django-quilla-web/actions/runs/4659895485
firefox
https://github.com/Scot3004/django-quilla-web/actions/runs/4659928322

Tomar screenshot en test del homepage

---

scripts/events.py
tests/conftest.py

Closes #395 
Esta es la salida del comando despues de estos cambios
```bash
$ pylint --recursive=y tests scripts
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

395 fixes pylint

---

content/blog/como-fue-organizar-primer-django-girls-barranquilla/contents+en.lr

Related to #404
Trabajo en progreso

traduccion de articulo django girls 2017

---

models/proyecto.ini
models/proyectos.ini
templates/macros/title.html
templates/page.html
templates/proyecto.html
templates/proyectos.html

Parte 1 #126 
No se incluye content.lr
Asi se ve cuando se escoge el modelo proyecto para una nueva página
Y para el detalle de cada proyecto

Modelos de proyecto, con plantilla minima

---

content/contacto/contents.lr

Closes #411 
Corrije el titulo en la página de contacto

Ocultar titulo en página contacto

---

django-quilla.lektorproject

Closes #421
El unico cambio en el proyecto está en agregar anchors en campos de titulo de campos markdown. No se afecta nada mas en el proyecto y ejecutó sin errores en el codespace.

added-lektor-markdown-header-anchors

---

content/proyectos/django-girls-barranquilla/contents.lr
content/proyectos/pagina-web/contents.lr
databags/nosotros.json
models/proyecto.ini
templates/blocks/inactive-members.html
templates/macros/miembros.html
templates/nosotros-miembro.html
templates/proyecto.html

Parte 6 #126 
Se hizo primero por que me parecio que la traducción y la integración con la api de github se puede hacer despues
Asi se ve cuando se están agregando los miembros en la vista de proyectos
Se agrega un listado de organizadores y colaboradores por proyecto
En la vista de miembros los organizadores se ven asi
En la vista de miembros los colaboradores se ven asi

Projecto miembros

---

.github/workflows/actualizar-eventos-meetup.yml

Closes #280 
Creacion de workflow para para ejecutar semanalmente el script events.py. Si hay cambios en el archivo meetup.json generar automaticamente un pull request para solicitar el merge de esos cambios.

Actualizar eventos meetup

---

content/blog/generalidades-ingenieria-datos/contents+en.lr
content/codigo-de-conducta/contents.lr
content/nosotros/andres-perez/contents+en.lr
content/nosotros/andres-perez/contents.lr
content/nosotros/brayan-garcia/contents+en.lr
content/nosotros/brayan-garcia/contents.lr
content/nosotros/cesar-herdenez/contents+en.lr
content/nosotros/cesar-herdenez/contents.lr
content/nosotros/fernando-llinas/contents+en.lr
content/nosotros/fernando-llinas/contents.lr
content/nosotros/javier-daza/contents+en.lr
content/nosotros/javier-daza/contents.lr
content/nosotros/javier-fonseca/contents+en.lr
content/nosotros/javier-fonseca/contents.lr
content/nosotros/jorge-rueda/contents+en.lr
content/nosotros/jose-caro/contents+en.lr
content/nosotros/jose-caro/contents.lr
content/nosotros/katherine-lora/contents+en.lr
content/nosotros/katherine-lora/contents.lr
content/nosotros/leonardo-orozco/contents+en.lr
content/nosotros/leonardo-orozco/contents.lr
content/nosotros/paula-aragon/contents+en.lr
content/nosotros/paula-aragon/contents.lr
content/nosotros/sergio-molinares/contents+en.lr
content/nosotros/sergio-orozco/contents+en.lr
content/nosotros/sergio-orozco/contents.lr
content/nosotros/yudy-herrera/contents+en.lr
content/nosotros/yudy-herrera/contents.lr
content/nosotros/yuliana-martinez/contents+en.lr
content/nosotros/yuliana-martinez/contents.lr

Actualización miembros de equipo
Se mueven ciertos miembros de posición y se diligencia nueva información de algunas personas del equipo

Se actualiza información del equipo

---

content/proyectos/contents+en.lr
content/proyectos/django-girls-barranquilla/contents+en.lr
content/proyectos/formacion-emprendedora/contents+en.lr
content/proyectos/katsu/contents+en.lr
content/proyectos/mercadeo-digital/contents+en.lr
content/proyectos/pagina-web/contents+en.lr
content/proyectos/temii/contents+en.lr

Closes #126 
Traducción al inglés de los proyectos

docs: Traduccion de la seccion de proyectos al inglés

---

requirements.txt

Según mi smoke test no se rompe nada. Quedo a la espera de las sugerencias de los demás

build: Se actualizan dependencias de paquetes python

---

templates/layouts/footer.html

chore: Actualizo footer con enlace a canal de WA

---

packages/speaker-events/.gitignore
packages/speaker-events/README.md
packages/speaker-events/lektor_speaker_events.py
packages/speaker-events/setup.cfg
packages/speaker-events/setup.py
templates/nosotros-miembro.html

Relacionado con #394 
Plugin para buscar los eventos de un speaker con el modelo cargado anteriormente

Plugin speaker event

---

scripts/create_events.py

Relacionado con #394 
Script de migración de eventos toma los contenidos del databag y los combina con la busqueda en flowblock de eventos

Script de creación de eventos para migracion

---

content/eventos/2023-03-02-deepdream-visualizando-que-aprende-una-red-neuronal-convolucional/contents.lr
content/eventos/2023-04-27-linux-amigable/contents.lr
content/eventos/2023-06-22-del-llm-al-chatbot-como-funcionan-su-entrenamiento-y-produccion-sin-usar-gpu/contents.lr
content/eventos/2023-07-27-modelado-de-data-warehouses-con-dbt/contents.lr
content/eventos/2023-11-30-analisis-y-estadistica-de-fifa-24/contents.lr
content/eventos/2024-03-21-analisis-geoespacial-con-python-y-qgis/contents.lr

Formato para los eventos 2023
Tener en cuenta que no se formatearon los eventos sin ponentes

Formato en detalles a eventos del 2023

---

templates/eventos.html

Relacionado con #394
Numeral 8. Paginación de eventos
Habilita la paginación en las páginas de eventos

Paginación de eventos

---

.github/workflows/actualizar-eventos-meetup.yml
scripts/create_events.py

Closes #502 
Evento ya aparece listado
action ejecutado con actualizar eventos
https://github.com/PyBAQ/website/actions/runs/8988388765
Pull request creado satisfactoriamente
https://github.com/PyBAQ/website/pull/504
Por cierto, este PR no actualiza eventos, así que el preview deploy de este no da el feedback del cambio realizado
El verdadero preview deploy es el del pr generado despues de la ejecución del script
https://deploy-preview-504--vigilant-neumann-d109b9.netlify.app/eventos/

Script para actualizar eventos ejecutado desde action

---

content/eventos/2024-05-02-por-que-son-importantes-los-contest-de-programacion/contents.lr

Formato del evento de mayo siguiendo las lineas de los otros pr

Charla carlos sierra información basica

---

.github/workflows/actualizar-eventos-meetup.yml
scripts/create_events.py

Closes #511 
https://github.com/PyBAQ/website/actions/runs/9387555377/job/25850745572

Script eventos fix

---

.github/workflows/deploy.yml

Closes #518 
En el job que ejecute no aparecen advertencias
https://github.com/PyBAQ/website/actions/runs/9605423253/job/26493019941
El único paso que no se ejecuta es `Desplegar pagina pybaq` pero ese solo lo podemos ver en master en el repo de pybaq, entonces toca hacer merge y a la de dios 😆

Actualización de actions deploy.yml

---

README.md
install.md

Closes #523 
Se reorganiza todo el readme para dar información mas valiosa en vez de irnos al detalle de como instalar python, adicional se colocaron los nuevos badges que reemplazan al badge de travis
[Ver readme](https://github.com/PyBAQ/website/blob/27a4ad52f088bc8a06e08f8b253ee8a7208ed26d/README.md)

Reorganizado el readme con nuevos post y badges de github

---

.github/workflows/test-e2e.yml

Esta relacionado con el hallazgo de #518 solo que es otro workflow, la solución es similar
Se ejecuto en firefox y chrome
https://github.com/PyBAQ/website/actions/runs/9621759566
https://github.com/PyBAQ/website/actions/runs/9621758054

Actualizados action de workflow test-e2e

---

content/blog/tutorial-de-web-scraping-y-beautifulsoup/contents.lr
content/blog/una-guia-completa-de-django-para-principiantes-parte-1/contents.lr
content/blog/una-guia-completa-de-django-para-principiantes-parte-2/contents.lr

Esta relacionado con issues #469 y #470
- Incluyo video de charla en Python Chile sobre web scrapping al artículo de web scraping con beautifulsoup
- Renderizo tabla contenidos guia de django partes 1 y 2
- Actualizo titulos H2 y H3 en guia de django parte 2

Actualización contenido de artículos

---

content/nosotros/fernando-llinas/contents+en.lr
content/nosotros/jorge-rueda/contents+en.lr
content/nosotros/m-camila-arciniegas-pua/contents+en.lr
content/nosotros/rashel-carey/contents+en.lr

- La página de "nosotros" en inglés estaba desactualizada

docs: Se actualiza pagina en ingles de 'nosotros'

---

content/eventos/2017-01-30-aprendamos-a-hacer-testing-con-mock/contents.lr
content/eventos/2017-02-10-pycon-colombia-2017/contents.lr
content/eventos/2017-03-14-celery-y-tareas-asincronas/contents.lr
content/eventos/2017-04-17-pimpeando-tu-antigua-version-de-django/contents.lr
content/eventos/2017-05-04-aprende-machine-learning-basico-jugando-con-python-y-flappy-bird/contents.lr
content/eventos/2017-06-01-como-crear-un-teclado-virtual-con-tecnicas-de-vision-por-computadora/contents.lr
content/eventos/2017-07-13-campo-de-juego-para-emprendedores/contents.lr
content/eventos/2017-07-15-post-evento-django-girls/contents.lr
content/eventos/2017-07-17-construyamos-un-software-de-reconocimiento-de-rostros-en-una-microcomputadora/contents.lr
content/eventos/2017-08-22-aprendamos-las-bases-de-python/contents.lr
content/eventos/2017-08-30-programadores-vamos-a-comer/contents.lr
content/eventos/2017-09-18-beneficios-tributarios-para-freelancers-emprendedores-y-empresas-tic/contents.lr
content/eventos/2017-10-19-traduccion-automatica-usando-redes-neuronales/contents.lr
content/eventos/2017-11-23-herramientas-para-hacer-ciencia-con-python/contents.lr
content/eventos/2017-12-19-reconocimiento-facial-con-redes-neuronales-usando-tensorflow-y-python/contents.lr

Actualización de contenido
Ninguna

Actualizo eventos de 2017

---

content/eventos/2019-01-18-bienvenida-2019-y-reunion-abierta-equipo-pybaq/contents.lr
content/eventos/2019-01-29-finanzas-cuantitativas-para-analisis-de-mercados-app-del-manto-de-la-tierra/contents.lr
content/eventos/2019-02-26-crea-un-sitio-web-en-tiempo-real-tipo-google-doc-creando-comunidades-exitosas/contents.lr
content/eventos/2019-03-28-un-algoritmo-artistico-de-estilo-neural-pybaq-detras-del-escenario/contents.lr
content/eventos/2019-04-25-estudiar-machine-learning-en-el-exterior-intro-a-la-vision-por-computador/contents.lr
content/eventos/2019-05-30-app-serverless-y-auto-escalable-con-aws-lambda-consigue-un-trabajo-en-dolares/contents.lr
content/eventos/2019-06-06-inteligencia-artificial-y-sus-aplicaciones-ciberseguridad-vectores-de-ataque/contents.lr
content/eventos/2019-07-06-taller-de-programacion-para-mujeres-barranquilla/contents.lr
content/eventos/2019-07-30-webrtc-y-si-hacemos-un-skype-primeros-pasos-en-numpy/contents.lr
content/eventos/2019-08-29-multimodal-video-analytics-data-science-the-new-age-revolution/contents.lr
content/eventos/2019-09-26-capturando-credenciales-en-google-chrome-con-drf-drf-elasticsearch/contents.lr
content/eventos/2019-10-24-procesamiento-de-imagenes-de-tejido-con-python-project-management-101/contents.lr
content/eventos/2019-11-28-conociendo-oauth2-python-para-principiantes-donde-empezar/contents.lr
content/eventos/2019-12-19-piloteando-docker-usando-python-saca-provecho-a-eventos-internacionales/contents.lr

Relacionado con #394 
Organiza la información de los eventos de 2019
La observación de la pizza esta en un blockquote, para que se vea bonito se requiere integrar #535 
Se eliminaron los siguientes links rotos
2019-07-06
Taller de programación mujeres
https://pybaq.co/eventos/2019-07-06-taller-de-programacion-para-mujeres-barranquilla/
http://tallerdeprogramacion.co/
Habian 2 eventos estilo pycon pero aunque habian 2 charlas solo habia 1 video de youtube en cada una, le anexe el youtube a la charla que se puede ver en youtube para facilitarle la vida a las personas que entran al post 😸

Eventos 2019

---

content/eventos/2018-01-18-conectando-flask-con-vuejs-en-el-desarrollo-de-una-single-page-application/contents.lr
content/eventos/2018-02-26-como-crear-una-empresa-en-usa-sin-morir-en-el-intento-pasarelas-de-pago/contents.lr
content/eventos/2018-03-22-segmentacion-y-caracterizacion-de-imagenes-de-celulas-tomadas-por-microscopio/contents.lr
content/eventos/2018-04-19-introduccion-a-django-cms-y-creacion-de-plugins-personalizados/contents.lr
content/eventos/2018-05-24-zen-de-python-saca-el-mejor-provecho-a-redis/contents.lr
content/eventos/2018-06-14-carros-autonomos-creacion-de-apis-para-tus-apps/contents.lr
content/eventos/2018-07-17-emprender-con-inteligencia-artficial-intro-analisis-de-datos-con-jupyter/contents.lr
content/eventos/2018-08-16-integrar-graphql-a-django-entiende-el-poder-de-los-datos-con-spark/contents.lr
content/eventos/2018-09-17-disena-tu-proyecto-de-machine-learning-patrones-de-automatizacion-de-pruebas/contents.lr
content/eventos/2018-10-20-meetup-hacktoberfest-baq/contents.lr
content/eventos/2018-10-23-ciencia-de-datos-para-dummies-define-y-estructura-un-proyecto-personal/contents.lr
content/eventos/2018-11-19-seguridad-informatica-en-la-web-aprender-ingles-ahora-es-mejor-que-nunca/contents.lr
content/eventos/2018-12-11-powerbi-y-python-inteligencia-de-negocios-introduccion-a-servicios-de-aws/contents.lr

Ninguno. Mejora de los eventos
- El Wayner del evento de diciembre de 2018 es otra persona. Favor no confundir con [https://pybaq.co/nosotros/wayner-barrios/](https://pybaq.co/nosotros/wayner-barrios/)
- No encontré las diapositivas de la charla de @andoresuperesu así que puse un enlace hacia su repositorio (donde aún están las notas de la charla)

Actualización de eventos de 2018

---

content/eventos/2015-03-31-1er-meetup-django-barranquilla/contents.lr
content/eventos/2015-06-16-5to-meetup-django-barranquilla/contents.lr
content/eventos/2015-06-30-6to-meetup-django-barranquilla/contents.lr
content/eventos/2015-07-13-7mo-meetup-django-barranquilla/contents.lr
content/eventos/2015-08-03-8vo-meetup-django-barranquilla/contents.lr
content/eventos/2015-11-03-14vo-meetup-django-barranquilla/contents.lr
content/eventos/2016-01-07-bienvenida-de-ano-2016-django-barranquilla/contents.lr
content/eventos/2016-02-15-como-usar-django-smart-selects/contents.lr
content/eventos/2016-03-15-introduccion-a-la-vision-por-computadora/contents.lr
content/eventos/2016-05-02-como-crear-sitios-web-estaticos-con-lektor/contents.lr
content/eventos/2016-06-13-como-crear-sitios-web-estaticos-con-lektor/contents.lr
content/eventos/2016-08-08-integrando-una-aplicacion-en-django-con-otros-servicios/contents.lr
content/eventos/2016-09-05-django-smart-select-y-flask-microframework/contents.lr
content/eventos/2017-05-04-aprende-machine-learning-basico-jugando-con-python-y-flappy-bird/contents.lr
content/eventos/2017-09-18-beneficios-tributarios-para-freelancers-emprendedores-y-empresas-tic/contents.lr

Una mejora de las descripciones anteriores
- Hacían falta algunas diapositivas
- Borre enlaces rotos

fix: Arreglo enlaces rotos y agrego enlaces diapositivas

---

content/politica-de-salud-y-seguridad/contents+en.lr
content/politica-de-salud-y-seguridad/contents.lr
databags/footer.json
templates/layouts/footer.html

Ninguna
Requerimiento para el grant

Politica de salud y seguridad

---

content/eventos/2024-10-17-desarrollo-basado-en-pruebas-codificando-con-calidad-superior-de-cero-a-gpt/contents.lr

Ninguno
Actualizo adjuntos charlas octubre 2024

docs: Adjuntos de charla octubre 2024

---

content/nosotros/javier-daza/contents+en.lr
content/nosotros/javier-daza/contents.lr
models/nosotros-miembro.ini
templates/macros/miembros.html
templates/nosotros-miembro.html

Mostrar Linkedin como red social para perfiles #530

Mostrar Linkedin como red social para perfiles #530

---

content/nosotros/sergio-orozco/contents.lr

En base que en #570 ya hace que se pueda agregar linkedin en la pagina de nosotros, coloco el mio 👍🏼

añadido linkedin sergio orozco

---

.github/workflows/actualizar-eventos-meetup.yml

Actualizar meetup.gql en script

Commit incluye meetup_gql.json
